name: Snake Animation Generator

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate snake animation files
        uses: platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg?palette=github-dark&color_snake=#7c3aed&color_dots=#0d1117,#1a1a2e,#16213e,#0f3460,#533483
            github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00d4ff&color_dots=#0a0e27,#1e2761,#3c56a6,#5b7ec8,#7aa6eb
            github-contribution-grid-snake-light.svg?palette=github-light&color_snake=#ff6b35&color_dots=#f0f0f0,#c6e48b,#7bc96f,#239a3b,#196127

      - name: Update repository with snake files
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Get the latest state of the repository
          git fetch origin
          git checkout main
          git reset --hard origin/main
          
          # Stage the snake files
          git add github-contribution-grid-snake*.svg
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to snake files"
          else
            echo "Committing updated snake files"
            git commit -m "🐍 Update snake animation [skip ci]"
            
            # Push with retry logic
            for i in {1..3}; do
              if git push origin main; then
                echo "Successfully pushed changes"
                break
              else
                echo "Push failed, attempt $i/3"
                git fetch origin
                git rebase origin/main
                sleep 2
              fi
            done
          fi
